### ISSUE TITLE
Failed to resolve entry for package "@tybalt/core". The package may have incorrect main/module/exports specified in its package.json.

### ISSUE THREAD

**Issue by doug-wade** [doug-wade/tybalt#302]
```shell
10:53:55 PM [vite] Internal server error: Failed to resolve entry for package "@tybalt/core". The package may have incorrect main/module/exports specified in its package.json.
  Plugin: vite:import-analysis
  File: /home/doug/workspace/lemmy-web-component/components/LemmyThread/lemmy-thread.ts
      at packageEntryFailure (file:///home/doug/workspace/lemmy-web-component/node_modules/vite/dist/node/chunks/dep-abb4f102.js:28698:11)
      at resolvePackageEntry (file:///home/doug/workspace/lemmy-web-component/node_modules/vite/dist/node/chunks/dep-abb4f102.js:28695:5)
      at tryNodeResolve (file:///home/doug/workspace/lemmy-web-component/node_modules/vite/dist/node/chunks/dep-abb4f102.js:28429:20)
      at Context.resolveId (file:///home/doug/workspace/lemmy-web-component/node_modules/vite/dist/node/chunks/dep-abb4f102.js:28190:28)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.resolveId (file:///home/doug/workspace/lemmy-web-component/node_modules/vite/dist/node/chunks/dep-abb4f102.js:44130:32)
      at async TransformContext.resolve (file:///home/doug/workspace/lemmy-web-component/node_modules/vite/dist/node/chunks/dep-abb4f102.js:43846:23)
      at async normalizeUrl (file:///home/doug/workspace/lemmy-web-component/node_modules/vite/dist/node/chunks/dep-abb4f102.js:41722:34)
      at async file:///home/doug/workspace/lemmy-web-component/node_modules/vite/dist/node/chunks/dep-abb4f102.js:41874:47
      at async Promise.all (index 0) (x2)
```

**Comment by doug-wade** [comment]
in the package, the directory is `mjs`

```
» ls node_modules/@tybalt/core/dist
cjs  mjs  types
```

in package.json, its `esm`

```
"module": "dist/esm/index.js",
```

`test-utils` uses `mjs` for both, so we should change the `module` field

```
"module": "dist/mjs/index.js",
```
