### ISSUE TITLE
Add support for node 20

### ISSUE THREAD

**Issue by doug-wade** [doug-wade/tybalt#311]
I had to take it out of `yarn-test.yaml` because I was getting this error on ci

```shell
ERROR  run failed: command  exited (1)
  cache miss, executing 8395105eb3d0d5d8
  TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /home/runner/work/tybalt/tybalt/packages/cli/src/index.ts
      at new NodeError (node:internal/errors:405:5)
      at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:99:9)
      at defaultGetFormat (node:internal/modules/esm/get_format:142:36)
      at defaultLoad (node:internal/modules/esm/load:91:20)
      at nextLoad (node:internal/modules/esm/hooks:733:28)
      at load (/home/runner/work/tybalt/tybalt/node_modules/ts-node/dist/child/child-loader.js:19:122)
      at nextLoad (node:internal/modules/esm/hooks:733:28)
      at Hooks.load (node:internal/modules/esm/hooks:377:26)
      at MessagePort.handleMessage (node:internal/modules/esm/worker:[168](https://github.com/doug-wade/tybalt/actions/runs/5664876807/job/15348837535?pr=296#step:6:183):24)
      at [nodejs.internal.kHybridDispatch] (node:internal/event_target:778:20) {
    code: 'ERR_UNKNOWN_FILE_EXTENSION'
  }
  FAIL tst/index.test.ts
    cli
      ✕ should emit the version (2655 ms)
  
    ● cli › should emit the version
  
      Command failed: npx ts-node-esm /home/runner/work/tybalt/tybalt/packages/cli/src/index.ts --version
      TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /home/runner/work/tybalt/tybalt/packages/cli/src/index.ts
  
  
  
        at load (../../node_modules/ts-node/dist/child/child-loader.js:19:122)
        at [nodejs.internal.kHybridDispatch] (node:internal/event_target:778:20) {
          code: 'ERR_UNKNOWN_FILE_EXTENSION'
        }
        at Object.<anonymous> (tst/index.test.ts:29:55)
  
  Test Suites: 1 failed, 1 total
  Tests:       1 failed, 1 total
  Snapshots:   0 total
  Time:        3.381 s
  Ran all test suites.
```

**Comment by doug-wade** [comment]
Resolved in https://github.com/doug-wade/tybalt/pull/520
